### ISSUE TITLE
Some Patterns return undefined

### ISSUE THREAD

**Issue by emorling** [cm45t3r/candlestick#12]
When examining series some return empty arrays, and other several undefined values. Is this to be expected?

**Comment by csidi90** [comment]
experiencing the same all values undefined

**Comment by nfcurti** [comment]
Finding the same issue, array looks good but it returns undefined, tried with hammer and hangingMen

**Comment by cm45t3r** [comment]
Hi @emorling, @csidi90, and @nfcurti,

Thank you for reporting this issue. After almost 2 years, I could fix the `undefined` issue, so you are welcome to test it :)

Please, beware of the breaking changes explained below. Let me know if you prefer to keep the former behavior and I can add some options allowing to return the object instead of indexes from `dataArray`, and/or last affected index/value in the pattern (in cases where two or more candlesticks are involved in conforming the pattern, e.g. engulfings).


**=== :warning: BREAKING CHANGE WARNING ON VERSIONS `>= 0.0.6` ===**

**Before:** search pattern functions return the *last* OHLC object conforming the pattern.
**After:** they return the *first* **index** of the candle conforming the pattern. It helps 
locating candlestick in `dataArray` more easily. So before upgrading to version 0.0.6, please 
be aware of changing your code.
